enable_table_row_count_monitoring: true
log_level: "info"  # Optional values: "debug", "info", "warn", "error", "fatal", "panic"

sync_configs:
  - type: "mongodb"
    enable: true
    source_connection: "mongodb://localhost:27017"
    target_connection: "mongodb://localhost:27017"
    mongodb_resume_token_path: "/tmp/state/mongodb_resume_token"
    mappings:
      - source_database: "source_db"
        target_database: "target_db"
        tables:
          - source_table: "users"
            target_table: "users"

  - type: "mysql"
    enable: true
    source_connection: "root:root@tcp(localhost:3306)/source_db"
    target_connection: "root:root@tcp(localhost:3306)/target_db"
    mysql_position_path: "/tmp/state/mysql_position"
    mappings:
      - source_database: "source_db"
        target_database: "target_db"
        tables:
          - source_table: "users"
            target_table: "users"

  - type: "mariadb"
    enable: true
    source_connection: "root:root@tcp(localhost:3307)/source_db"
    target_connection: "root:root@tcp(localhost:3307)/target_db"
    mysql_position_path: "/tmp/state/mariadb_position"
    mappings:
      - source_database: "source_db"
        target_database: "target_db"
        tables:
          - source_table: "users"
            target_table: "users"

  - type: "postgresql"
    enable: true
    source_connection: "postgres://root:root@localhost:5432/source_db?sslmode=disable"
    target_connection: "postgres://root:root@localhost:5432/target_db?sslmode=disable"
    pg_position_path: "/tmp/state/pg_position"
    pg_replication_slot: "sync_slot"
    pg_plugin: "pgoutput"
    pg_publication_names: "mypub"
    mappings:
      - source_database: "source_db"
        source_schema: "public"
        target_database: "target_db"
        target_schema: "public"
        tables:
          - source_table: "users"
            target_table: "users"

  - type: "redis"
    enable: true
    source_connection: "redis://localhost:6379/0"
    target_connection: "redis://localhost:6379/1"
    redis_position_path: "/tmp/state/redis_position"
    mappings:
      - source_database: "db0"
        target_database: "db1"
        tables:
          - source_table: "source_stream"  # Redis Stream Name
            target_table: "" 